version: "3.9"

services:

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-lab_db}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  parser:
    build: ./parser_service
    restart: unless-stopped
    environment:
      DB_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-lab_db}
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy

  app:
    build: ./app
    restart: unless-stopped
    environment:
      DB_ADMIN: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-lab_db}
      JWT_SECRET: ${JWT_SECRET:-change_this_secret_in_env_file}
      PARSER_SERVICE_URL: http://parser:8001
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      parser:
        condition: service_started

  celery_worker:
    build: ./app
    restart: unless-stopped
    command: celery -A celery_app worker --loglevel=info
    environment:
      DB_ADMIN: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-lab_db}
      JWT_SECRET: ${JWT_SECRET:-change_this_secret_in_env_file}
      PARSER_SERVICE_URL: http://parser:8001
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      parser:
        condition: service_started

volumes:
  pgdata:
